version: '3.8'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile  # This Dockerfile installs Node.js
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app  # Mount the current directory to the container
      - /usr/src/app/node_modules  # Avoid mounting node_modules to prevent conflicts
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=library
    networks:
      - backend
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - backend

  vscode:
    image: codercom/code-server:latest
    container_name: vscode_container
    restart: always
    ports:
      - "8443:8080"
    volumes:
      - .:/home/coder/project
    environment:
      PASSWORD: "yourpassword"
      SUDO_PASSWORD: "yourpassword"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
